# Generated by Django 4.2.2 on 2023-10-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestions',
            name='subquestiontext',
            field=models.CharField(default='', max_length=200),
        ),
    ]
