# Generated by Django 4.2.2 on 2023-11-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medassistapp', '0002_subquestions_subquestiontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('emailid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dob', models.CharField(default='', max_length=200)),
                ('mobileno', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('userphoto', models.ImageField(blank=True, default='', upload_to='static/')),
            ],
        ),
    ]
